name: Build and Push to AWS ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REPOSITORY: wrap-it-api
      ECR_PUBLIC_REGISTRY_ALIAS: ${{ secrets.ECR_PUBLIC_REGISTRY_ALIAS }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to AWS Public ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public
        env:
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Java Application
        run: mvn clean package -DskipTests

      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG="latest"
          ECR_PUBLIC_URI="public.ecr.aws/${{ secrets.ECR_PUBLIC_REGISTRY_ALIAS }}/${{ env.ECR_REPOSITORY }}"
          
          echo "Building Docker image: $ECR_PUBLIC_URI:$IMAGE_TAG"
          docker build -t $ECR_REPOSITORY .
          docker tag $ECR_REPOSITORY:latest $ECR_PUBLIC_URI:$IMAGE_TAG
          echo "Pushing Docker image to AWS ECR..."
          docker push $ECR_PUBLIC_URI:$IMAGE_TAG
